### ISSUE TITLE
schować panią w sekcji dawkowanie

### ISSUE THREAD

**Issue by Domi-eStore** [eStoreLabs/RC---230322-SF-23-Magne-Forte-100-GENERIC#1]
ma się rozwijać razem z resztą info i chować.
Jak przerzucam <img> za <p class="es-dose__subtitle"> button górny traci bg color

**Comment by maetusz** [comment]
zrobione, ale nie mogę wrzucić tutaj, bo chyba nie mam uprawnień, wywala mi błąd, paczka w mailu
